const data = [
{id:1 ,team_home: "Aarhus Ultimate",team_home_score: 12,team_away: "Cph Hucks",team_away_score: 4, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:2 ,team_home: "Aarhus Ultimate",team_home_score: 8,team_away: "DTU Ultimate",team_away_score: 2, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:3 ,team_home: "Aarhus Ultimate",team_home_score: 13,team_away: "KFK",team_away_score: 8, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:4 ,team_home: "Aarhus Ultimate",team_home_score: 13,team_away: "Cph Hucks",team_away_score: 4, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:5 ,team_home: "Aarhus Ultimate",team_home_score: 13,team_away: "DTU Ultimate",team_away_score: 0, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:6 ,team_home: "Aarhus Ultimate",team_home_score: 13,team_away: "DTU Ultimate",team_away_score: 3, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:7 ,team_home: "Aarhus Ultimate",team_home_score: 10,team_away: "KFK",team_away_score: 7, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:8 ,team_home: "Aarhus Ultimate",team_home_score: 13,team_away: "KFK",team_away_score: 7, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:9 ,team_home: "Cph Hucks",team_home_score: 9,team_away: "KFK",team_away_score: 8, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:10 ,team_home: "Cph Hucks",team_home_score: 13,team_away: "Ultimate Dragons",team_away_score: 4, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:11 ,team_home: "Cph Hucks",team_home_score: 9,team_away: "DTU Ultimate",team_away_score: 4, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:12 ,team_home: "Cph Hucks",team_home_score: 10,team_away: "DTU Ultimate",team_away_score: 3, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:13 ,team_home: "Cph Hucks",team_home_score: 5,team_away: "KFK",team_away_score: 12, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:14 ,team_home: "Cph Hucks",team_home_score: 4,team_away: "KFK",team_away_score: 10, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:15 ,team_home: "DTU Ultimate",team_home_score: 8,team_away: "Ultimate Dragons",team_away_score: 3, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:16 ,team_home: "DTU Ultimate",team_home_score: 2,team_away: "VG Ultimate",team_away_score: 11, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:17 ,team_home: "KFK",team_home_score: 10,team_away: "DTU Ultimate",team_away_score: 4, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:18 ,team_home: "VG Ultimate",team_home_score: 8,team_away: "KFK",team_away_score: 13, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:19 ,team_home: "Aarhus Ultimate 1",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 4, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:20 ,team_home: "Aarhus Ultimate 2",team_home_score: 4,team_away: "Aalborg Dinosaurs",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:21 ,team_home: "Aarhus Ultimate 2",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 8, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:22 ,team_home: "Aarhus Ultimate 2",team_home_score: 8,team_away: "Aarhus Ultimate 1",team_away_score: 12, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:23 ,team_home: "AUC Mojn",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 0, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:24 ,team_home: "AUC Mojn",team_home_score: 0,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:25 ,team_home: "AUC Mojn",team_home_score: 12,team_away: "Aarhus Ultimate 2",team_away_score: 5, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:26 ,team_home: "AUC Mojn",team_home_score: 0,team_away: "Aarhus Ultimate 2",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:27 ,team_home: "AUC Mojn",team_home_score: 1,team_away: "Aarhus Ultimate 2",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:28 ,team_home: "Discflyers",team_home_score: 9,team_away: "Aalborg Dinosaurs",team_away_score: 10, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:29 ,team_home: "Discflyers",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 0, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:30 ,team_home: "Discflyers",team_home_score: 5,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:31 ,team_home: "Discflyers",team_home_score: 11,team_away: "Aarhus Ultimate 2",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:32 ,team_home: "Discflyers",team_home_score: 13,team_away: "AUC Mojn",team_away_score: 6, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:33 ,team_home: "Discflyers",team_home_score: 11,team_away: "AUC Mojn",team_away_score: 7, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:34 ,team_home: "DTU Ultimate",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 0, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:35 ,team_home: "DTU Ultimate",team_home_score: 13,team_away: "Aarhus Ultimate 2",team_away_score: 1, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:36 ,team_home: "DTU Ultimate",team_home_score: 12,team_away: "Discflyers",team_away_score: 9, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:37 ,team_home: "Frederikssund",team_home_score: 4,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:38 ,team_home: "Frederikssund",team_home_score: 10,team_away: "AUC Mojn",team_away_score: 9, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:39 ,team_home: "Frederikssund",team_home_score: 9,team_away: "Discflyers",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:40 ,team_home: "Frederikssund",team_home_score: 11,team_away: "DTU Ultimate",team_away_score: 10, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:41 ,team_home: "Frederikssund",team_home_score: 13,team_away: "DTU Ultimate",team_away_score: 9, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:42 ,team_home: "Hucks",team_home_score: 6,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:43 ,team_home: "Hucks",team_home_score: 12,team_away: "Aarhus Ultimate 2",team_away_score: 2, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:44 ,team_home: "Hucks",team_home_score: 13,team_away: "AUC Mojn",team_away_score: 1, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:45 ,team_home: "Hucks",team_home_score: 11,team_away: "Discflyers",team_away_score: 10, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:46 ,team_home: "Hucks",team_home_score: 13,team_away: "Discflyers",team_away_score: 9, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:47 ,team_home: "Hucks",team_home_score: 6,team_away: "DTU Ultimate",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:48 ,team_home: "Hucks",team_home_score: 10,team_away: "Frederikssund",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:49 ,team_home: "KFK",team_home_score: 13,team_away: "Aarhus Ultimate 1",team_away_score: 6, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:50 ,team_home: "KFK",team_home_score: 13,team_away: "Aarhus Ultimate 2",team_away_score: 1, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:51 ,team_home: "KFK",team_home_score: 13,team_away: "AUC Mojn",team_away_score: 3, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:52 ,team_home: "KFK",team_home_score: 12,team_away: "DTU Ultimate",team_away_score: 5, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:53 ,team_home: "KFK",team_home_score: 13,team_away: "DTU Ultimate",team_away_score: 9, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:54 ,team_home: "KFK",team_home_score: 13,team_away: "Frederikssund",team_away_score: 8, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:55 ,team_home: "KFK",team_home_score: 13,team_away: "Frederikssund",team_away_score: 5, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:56 ,team_home: "KFK",team_home_score: 13,team_away: "Hucks",team_away_score: 2, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:57 ,team_home: "KFK Pirates",team_home_score: 11,team_away: "Aalborg Dinosaurs",team_away_score: 10, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:58 ,team_home: "KFK Pirates",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 10, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:59 ,team_home: "KFK Pirates",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 11, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:60 ,team_home: "KFK Pirates",team_home_score: 3,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:61 ,team_home: "KFK Pirates",team_home_score: 13,team_away: "Aarhus Ultimate 2",team_away_score: 0, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:62 ,team_home: "KFK Pirates",team_home_score: 8,team_away: "Discflyers",team_away_score: 11, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:63 ,team_home: "KFK Pirates",team_home_score: 13,team_away: "Discflyers",team_away_score: 4, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:64 ,team_home: "KFK Pirates",team_home_score: 8,team_away: "DTU Ultimate",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:65 ,team_home: "KFK Pirates",team_home_score: 8,team_away: "Frederikssund",team_away_score: 12, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:66 ,team_home: "KFK Pirates",team_home_score: 13,team_away: "Hucks",team_away_score: 7, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:67 ,team_home: "KFK Pirates",team_home_score: 1,team_away: "KFK",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:68 ,team_home: "Ragnarok",team_home_score: 13,team_away: "Aarhus Ultimate 1",team_away_score: 6, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:69 ,team_home: "Ragnarok",team_home_score: 13,team_away: "Aarhus Ultimate 1",team_away_score: 11, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:70 ,team_home: "Ragnarok",team_home_score: 13,team_away: "AUC Mojn",team_away_score: 2, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:71 ,team_home: "Ragnarok",team_home_score: 13,team_away: "DTU Ultimate",team_away_score: 3, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:72 ,team_home: "Ragnarok",team_home_score: 13,team_away: "Frederikssund",team_away_score: 5, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:73 ,team_home: "Ragnarok",team_home_score: 13,team_away: "Frederikssund",team_away_score: 2, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:74 ,team_home: "Ragnarok",team_home_score: 13,team_away: "Hucks",team_away_score: 1, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:75 ,team_home: "Ragnarok",team_home_score: 12,team_away: "KFK",team_away_score: 10, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:76 ,team_home: "Ragnarok",team_home_score: 13,team_away: "KFK",team_away_score: 10, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:77 ,team_home: "Ragnarok",team_home_score: 13,team_away: "KFK Pirates",team_away_score: 2, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:78 ,team_home: "Ragnarok 2",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 12, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:79 ,team_home: "Ragnarok 2",team_home_score: 7,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:80 ,team_home: "Ragnarok 2",team_home_score: 13,team_away: "Aarhus Ultimate 2",team_away_score: 3, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:81 ,team_home: "Ragnarok 2",team_home_score: 13,team_away: "AUC Mojn",team_away_score: 1, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:82 ,team_home: "Ragnarok 2",team_home_score: 13,team_away: "DTU Ultimate",team_away_score: 6, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:83 ,team_home: "Ragnarok 2",team_home_score: 7,team_away: "DTU Ultimate",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:84 ,team_home: "Ragnarok 2",team_home_score: 5,team_away: "Frederikssund",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:85 ,team_home: "Ragnarok 2",team_home_score: 11,team_away: "Hucks",team_away_score: 6, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:86 ,team_home: "Ragnarok 2",team_home_score: 13,team_away: "Hucks",team_away_score: 4, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:87 ,team_home: "Ragnarok 2",team_home_score: 6,team_away: "KFK",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:88 ,team_home: "Ragnarok 2",team_home_score: 3,team_away: "KFK Pirates",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:89 ,team_home: "Ragnarok 2",team_home_score: 9,team_away: "Ragnarok",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:90 ,team_home: "Tørring Disccontrol",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 7, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:91 ,team_home: "Tørring Disccontrol",team_home_score: 13,team_away: "Aalborg Dinosaurs",team_away_score: 0, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:92 ,team_home: "Tørring Disccontrol",team_home_score: 7,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:93 ,team_home: "Tørring Disccontrol",team_home_score: 12,team_away: "Aarhus Ultimate 1",team_away_score: 11, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:94 ,team_home: "Tørring Disccontrol",team_home_score: 8,team_away: "Aarhus Ultimate 2",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:95 ,team_home: "Tørring Disccontrol",team_home_score: 13,team_away: "AUC Mojn",team_away_score: 7, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:96 ,team_home: "Tørring Disccontrol",team_home_score: 13,team_away: "Discflyers",team_away_score: 8, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:97 ,team_home: "Tørring Disccontrol",team_home_score: 8,team_away: "Discflyers",team_away_score: 12, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:98 ,team_home: "Tørring Disccontrol",team_home_score: 5,team_away: "Frederikssund",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:99 ,team_home: "Tørring Disccontrol",team_home_score: 13,team_away: "Hucks",team_away_score: 9, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:100 ,team_home: "Tørring Disccontrol",team_home_score: 8,team_away: "KFK",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:101 ,team_home: "Tørring Disccontrol",team_home_score: 3,team_away: "Ragnarok",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:102 ,team_home: "Tørring Disccontrol",team_home_score: 0,team_away: "Ragnarok 2",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:103 ,team_home: "Ultimate Dragons",team_home_score: 6,team_away: "Aalborg Dinosaurs",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:104 ,team_home: "Ultimate Dragons",team_home_score: 4,team_away: "Aarhus Ultimate 1",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:105 ,team_home: "Ultimate Dragons",team_home_score: 13,team_away: "Aarhus Ultimate 2",team_away_score: 5, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:106 ,team_home: "Ultimate Dragons",team_home_score: 13,team_away: "AUC Mojn",team_away_score: 12, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:107 ,team_home: "Ultimate Dragons",team_home_score: 5,team_away: "DTU Ultimate",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:108 ,team_home: "Ultimate Dragons",team_home_score: 13,team_away: "DTU Ultimate",team_away_score: 7, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:109 ,team_home: "Ultimate Dragons",team_home_score: 8,team_away: "Frederikssund",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:110 ,team_home: "Ultimate Dragons",team_home_score: 13,team_away: "Hucks",team_away_score: 8, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:111 ,team_home: "Ultimate Dragons",team_home_score: 1,team_away: "KFK",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:112 ,team_home: "Ultimate Dragons",team_home_score: 13,team_away: "KFK Pirates",team_away_score: 9, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "2. DM runde",group:""},
{id:113 ,team_home: "Ultimate Dragons",team_home_score: 0,team_away: "Ragnarok",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne lørdag",group:""},
{id:114 ,team_home: "Ultimate Dragons",team_home_score: 4,team_away: "Ragnarok",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:115 ,team_home: "Ultimate Dragons",team_home_score: 13,team_away: "Ragnarok 2",team_away_score: 8, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "1. DM runde",group:""},
{id:116 ,team_home: "Ultimate Dragons",team_home_score: 0,team_away: "Tørring Disccontrol",team_away_score: 13, division: "Open",tournament: "DM",year:2018,type:"Gras",round: "Finalestævne søndag",group:""},
{id:117 ,team_home: "VG Ultimate",team_home_score: 10,team_away: "Ultimate Dragons",team_away_score: 11, division: "Women",tournament: "DM",year:2018,type:"Gras",round: "DM Midtsæson",group:""},
{id:118 ,team_home: "Aarhus",team_home_score: 13,team_away: "DTU 2",team_away_score: 2, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Pulje B"},
{id:119 ,team_home: "Aarhus",team_home_score: 10,team_away: "KFK",team_away_score: 6, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Pulje B"},
{id:120 ,team_home: "Aarhus",team_home_score: 12,team_away: "Ultimate Dragons",team_away_score: 6, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"S2"},
{id:121 ,team_home: "CPH Hucks",team_home_score: 12,team_away: "DTU 2",team_away_score: 8, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"5. plads"},
{id:122 ,team_home: "CPH Hucks",team_home_score: 7,team_away: "Ultimate Dragons",team_away_score: 10, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Pulje A"},
{id:123 ,team_home: "DTU",team_home_score: 13,team_away: "Aarhus",team_away_score: 12, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Finale"},
{id:124 ,team_home: "DTU",team_home_score: 10,team_away: "CPH Hucks",team_away_score: 5, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Pulje A"},
{id:125 ,team_home: "DTU",team_home_score: 13,team_away: "KFK",team_away_score: 9, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"S1"},
{id:126 ,team_home: "DTU",team_home_score: 10,team_away: "Ultimate Dragons",team_away_score: 7, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Pulje A"},
{id:127 ,team_home: "KFK",team_home_score: 13,team_away: "DTU 2",team_away_score: 0, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Pulje B"},
  {id:128 ,team_home: "KFK",team_home_score: 13,team_away: "Ultimate Dragons",team_away_score: 6, division: "Mixed",tournament: "DM",year:2019,type:"Gras",round: "Finalestævne",group:"Bronze"},

  {
    id: 129,
    team_home: "Aarhus",
    team_home_score: 13,
    team_away: "DTU 2",
    team_away_score: 2,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Pulje B"
  },
  {
    id: 130,
    team_home: "Aarhus",
    team_home_score: 10,
    team_away: "KFK",
    team_away_score: 6,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Pulje B"
  },
  {
    id: 131,
    team_home: "Aarhus",
    team_home_score: 12,
    team_away: "Ultimate Dragons",
    team_away_score: 6,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "S2"
  },
  {
    id: 132,
    team_home: "CPH Hucks",
    team_home_score: 12,
    team_away: "DTU 2",
    team_away_score: 8,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "5. plads"
  },
  {
    id: 133,
    team_home: "CPH Hucks",
    team_home_score: 7,
    team_away: "Ultimate Dragons",
    team_away_score: 10,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Pulje A"
  },
  {
    id: 134,
    team_home: "DTU",
    team_home_score: 13,
    team_away: "Aarhus",
    team_away_score: 12,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Finale"
  },
  {
    id: 135,
    team_home: "DTU",
    team_home_score: 10,
    team_away: "CPH Hucks",
    team_away_score: 5,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Pulje A"
  },
  {
    id: 136,
    team_home: "DTU",
    team_home_score: 13,
    team_away: "KFK",
    team_away_score: 9,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "S1"
  },
  {
    id: 137,
    team_home: "DTU",
    team_home_score: 10,
    team_away: "Ultimate Dragons",
    team_away_score: 7,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Pulje A"
  },
  {
    id: 138,
    team_home: "KFK",
    team_home_score: 13,
    team_away: "DTU 2",
    team_away_score: 0,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Pulje B"
  },
  {
    id: 139,
    team_home: "KFK",
    team_home_score: 13,
    team_away: "Ultimate Dragons",
    team_away_score: 6,
    division: "mixed",
    tournament: "DM",
    year: 2019,
    type: "Gras",
    round: "Finalestævne",
    group: "Bronze"
  }
];

export async function fetchPage(opts) {
  var indexStart = opts.page * opts.pageSize - opts.pageSize;

  let randomWaitTime = Math.floor(Math.random() * 5000);
  await sleep(randomWaitTime);

  let query = opts.args.query ? opts.args.query : "";

  // let filteredData = data.filter(license =>
  //   license.name.toLowerCase().includes(query.toLowerCase())
  // );
  console.log(opts);

  return {
    total: data.length,
    data: data.slice(indexStart, indexStart + opts.pageSize)
  };
}

function sleep(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}
